apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
spec:
  selector:
    matchLabels:
      app: nestjs-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:
      containers:
        - name: nestjs-k8s
          image: 19990106/testkube:latest
          ports:
            - containerPort: 3000
              resources:
                requests:
                  cpu: 100m
                limits:
                  cpu: 100m
      tolerations:
        - key: "key"
          operator: "Exists"
          effect: "NoSchedule"